name: All Applications
on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  common-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Elixir
        uses: actions/setup-elixir@v1.2.0
        with:
          elixir-version: 1.8
          otp-version: 22.2
          runs-on: ubuntu-latest
      - name: Run Static Checks
        run: |
          mix deps.get
          mix format --check-formatted
          mix credo
          mix sobelow
      - name: Run Unit
        run: |
          mix deps.get
          mix test
      - name: Run End to End Tests
        run: |
          mix deps.get
          mix test
  andi:
    runs-on: ubuntu-latest
    needs: common-checks
    steps:
      - uses: actions/checkout@v2
      - name: Check If Should Run
        id: pre_check
        run: |
          echo "::set-output name=should_run::false"
      - name: Setup Elixir
        if: steps.pre_check.outputs.should_run == 'true'
        uses: actions/setup-elixir@v1.2.0
        with:
          elixir-version: 1.8
          otp-version: 22.2
          runs-on: ubuntu-latest
      - name: Run Integration Tests
        if: steps.pre_check.outputs.should_run == 'true'
        run: |
          mix deps.get
          cd apps/andi
          mix test.integration

